Repository PrintingAlley/PrintingAlley-iOS, pull requests merged in 2023-10, with the labels that each got.

#30 🔀 :: 로그인화면과 로그인 후 마이페이 화면 연결
  Plugin/DependencyPlugin/ProjectDescriptionHelpers/ModulePaths.swift
  Projects/App/Sources/Application/NeedleGenerated.swift
  Projects/App/Sources/Application/SceneDelegate.swift
  Projects/App/Sources/DI/AppComponent+MyPage.swift
  Projects/Feature/MyPageModule/Interface/MyPageFactory.swift
  Projects/Feature/MyPageModule/Project.swift
  Projects/Feature/MyPageModule/Sources/DI/MyPageComponent.swift
  Projects/Feature/MyPageModule/Sources/DI/MyPageContentComponent.swift
  Projects/Feature/MyPageModule/Sources/Sources.swift
  Projects/Feature/MyPageModule/Sources/ViewControllers/MyPageContentViewController
  Projects/Feature/MyPageModule/Sources/ViewControllers/MyPageContentViewController.swift
  Projects/Feature/MyPageModule/Sources/ViewControllers/MyPageViewController.swift
  Projects/Feature/MyPageModule/Sources/ViewModel/MyPageViewModel.swift
  Projects/Feature/RooFuture/Project.swift
  Projects/Feature/RooFuture/Sources/ViewControllers/RootViewController.swift
  Projects/Feature/SignInFeature/Sources/ViewControllers/SignInViewController.swift
  Projects/Feature/SignInFeature/Sources/ViewModel/SignInViewModel.swift
  Projects/Shared/UtilityModule/Sources/Enum/LoginType.swift
  Projects/Shared/UtilityModule/Sources/Manager/PreferenceManager.swift
  Projects/Shared/UtilityModule/Sources/PreferenceModels/UserInfo.swift
  Projects/Shared/UtilityModule/Sources/Protocols/ContainerViewType.swift
  graph.png
Labels: ✨ Feat

#34 🔀 :: 네트워크 및 Jwt 토큰 저장소 모듈 구현
  Plugin/DependencyPlugin/ProjectDescriptionHelpers/ModulePaths.swift
  Projects/Core/JwtStore/Interface/JwtStore.swift
  Projects/Core/JwtStore/Project.swift
  Projects/Core/JwtStore/Sources/Jwt/KeychainJwtStore.swift
  Projects/Core/JwtStore/Testing/Testing.swift
  Projects/Core/Netwrok/Interface/interface.swift
  Projects/Core/Netwrok/Project.swift
  Projects/Core/Netwrok/Sources/API/AlleyAPI.swift
  Projects/Core/Netwrok/Sources/Error/AlleyError.swift
  Projects/Core/Netwrok/Sources/Plugin/CustomLoggingPlugin.swift
  Projects/Core/Netwrok/Sources/Plugin/JwtPlugin.swift
  Projects/Core/Netwrok/Sources/Secret/SecretURL.swift
  Projects/Core/Netwrok/Testing/Testing.swift
  Projects/Core/Netwrok/Tests/NetwrokTest.swift
  Projects/Domain/BaseDomain/Project.swift
  Projects/Feature/BaseFeature/Project.swift
  graph.png
Labels: ⚡️ Improve

#38 🔀 :: 디자인시스템 관련 코드 이동
  Projects/Shared/UtilityModule/Project.swift
  Projects/UserInterface/DesignSystem/Sources/Color/Color+PrintingAlley.swift
  Projects/UserInterface/DesignSystem/Sources/Color/PrintingAlleyColorSystem+Grey.swift
  Projects/UserInterface/DesignSystem/Sources/Color/PrintingAlleyColorSystem+MainBlue.swift
  Projects/UserInterface/DesignSystem/Sources/Color/PrintingAlleyColorSystem+Sub.swift
  Projects/UserInterface/DesignSystem/Sources/Color/PrintingAlleyColorable.swift
  Projects/UserInterface/DesignSystem/Sources/Font/Font+PrintingAlley.swift
  Projects/UserInterface/DesignSystem/Sources/Font/PrintingAlleyFontable.swift
  Projects/UserInterface/DesignSystem/Sources/Label/AlleyLabel.swift
  Projects/UserInterface/DesignSystem/Sources/Label/Extension+UILabel.swift
Labels: 🚚 Move

#43 🔀 :: 마이페이지 스켈리톤
  Projects/Feature/MyPageFeature/Sources/DI/MyPageContentComponent.swift
  Projects/Feature/MyPageFeature/Sources/Sources.swift
  Projects/Feature/MyPageFeature/Sources/ViewControllers/MyPageContentViewController.swift
  Projects/Feature/MyPageFeature/Sources/ViewControllers/MyPageViewController.swift
  Projects/Feature/MyPageFeature/Sources/ViewModel/MyPageContentViewModel.swift
  Projects/Feature/MyPageFeature/Sources/ViewModel/MyPageViewModel.swift
  Projects/Feature/MyPageFeature/Sources/Views/MyPageCategoryTableViewCell.swift
  Projects/Feature/MyPageFeature/Sources/Views/MyPageCollectionViewCell.swift
  Projects/Feature/MyPageFeature/Sources/Views/MyPageHeaderView.swift
  Projects/Feature/SignInFeature/Sources/ViewModel/SignInViewModel.swift
  Projects/Shared/UtilityModule/Sources/PreferenceModels/UserInfo.swift
  Projects/UserInterface/DesignSystem/Resources/Image/Icon.xcassets/Contents.json
  Projects/UserInterface/DesignSystem/Resources/Image/Icon.xcassets/profilePlaceHolder.imageset/Contents.json
  Projects/UserInterface/DesignSystem/Resources/Image/Icon.xcassets/profilePlaceHolder.imageset/person.circle.fill 1@2x.png
  Projects/UserInterface/DesignSystem/Resources/Image/Icon.xcassets/profilePlaceHolder.imageset/person.circle.fill 1@3x.png
  Projects/UserInterface/DesignSystem/Sources/Extensions/Extension+UIStackView.swift
  Projects/UserInterface/DesignSystem/Sources/Extensions/Extension+UIView.swift
  Projects/UserInterface/DesignSystem/Sources/Feature.swift
  Projects/UserInterface/DesignSystem/Sources/ImageButton/ImageButton.swift
  Projects/UserInterface/DesignSystem/Sources/Label/AlleyLabel.swift
Labels: ✨ Feat, ⚡️ Improve

#45 🔀 :: 구축한 네트워크 아키텍쳐 테스트
  Plugin/DependencyPlugin/ProjectDescriptionHelpers/ModulePaths.swift
  Projects/App/Project.swift
  Projects/App/Sources/Application/NeedleGenerated.swift
  Projects/App/Sources/DI/AppComponent+Auth.swift
  Projects/App/Support/Info.plist
  Projects/Core/Network/Interface/interface.swift
  Projects/Core/Network/Project.swift
  Projects/Core/Network/Sources/API/AlleyAPI.swift
  Projects/Core/Network/Sources/Error/AlleyError.swift
  Projects/Core/Network/Sources/Plugin/CustomLoggingPlugin.swift
  Projects/Core/Network/Sources/Plugin/JwtPlugin.swift
  Projects/Core/Network/Sources/Secret/SecretURL.swift
  Projects/Core/Network/Testing/Testing.swift
  Projects/Core/Network/Tests/NetwrokTest.swift
  Projects/Core/Netwrok/Project.swift
  Projects/Domain/AuthDomain/Interface/DI/AuthDomainFactory.swift
  Projects/Domain/AuthDomain/Interface/DataSource/RemoteAuthDataSource.swift
  Projects/Domain/AuthDomain/Interface/Entity/TestEntity.swift
  Projects/Domain/AuthDomain/Interface/Repository/AuthRepository.swift
  Projects/Domain/AuthDomain/Interface/UseCase/TestGetUseCase.swift
  Projects/Domain/AuthDomain/Project.swift
  Projects/Domain/AuthDomain/Sources/API/AuthAPI.swift
  Projects/Domain/AuthDomain/Sources/DI/AuthDomainComponent.swift
  Projects/Domain/AuthDomain/Sources/DTO/TestDTO.swift
  Projects/Domain/AuthDomain/Sources/DataSource/RemoteAuthDataSourceImpl.swift
  Projects/Domain/AuthDomain/Sources/Repository/AuthRepositoryImpl.swift
  Projects/Domain/AuthDomain/Sources/UseCase/TestGetUseCaseImpl.swift
  Projects/Domain/AuthDomain/Testing/Testing.swift
  Projects/Domain/AuthDomain/Tests/AuthDomainTest.swift
  Projects/Domain/BaseDomain/Interface/interface.swift
  Projects/Domain/BaseDomain/Project.swift
  Projects/Domain/BaseDomain/Sources/DataSource/BaseRemoteDataSource.swift
  Projects/Domain/BaseDomain/Sources/Feature.swift
  Projects/Feature/BaseFeature/Interface/interface.swift
  Projects/Feature/BaseFeature/Project.swift
  Projects/Feature/MyPageFeature/Project.swift
  Projects/Feature/RootFeature/Project.swift
  Projects/Feature/SignInFeature/Project.swift
  Projects/Feature/SignInFeature/Sources/DI/SignInComponent.swift
  Projects/Feature/SignInFeature/Sources/ViewModel/SignInViewModel.swift
  Projects/Shared/UtilityModule/Sources/PreferenceModel/UserInfo.swift
  graph.png
Labels: ✨ Feat, ⚡️ Improve

#48 🔀 :: 메일 시스템 및 Signing
  .gitignore
  Projects/Feature/MyPageFeature/Sources/ViewControllers/MyPageContentViewController.swift
  Projects/Feature/SignInFeature/Sources/ViewModel/SignInViewModel.swift
  Projects/Shared/UtilityModule/Sources/Utils/Utility.swift
Labels: ⚡️ Improve

#53 🔀 :: 디자인시스템 폰트 변경사항 적용
  Projects/Feature/MainTabFeature/Sources/ViewControllers/MainTabBarController.swift
  Projects/UserInterface/DesignSystem/Resources/Font/Pretendard-Medium.otf
  Projects/UserInterface/DesignSystem/Sources/Font/Font+PrintingAlley.swift
Labels: ⚡️ Improve

#57 🔀 홈뷰 모듈 생성
  Plugin/DependencyPlugin/ProjectDescriptionHelpers/ModulePaths.swift
  Projects/App/Project.swift
  Projects/App/Sources/Application/NeedleGenerated.swift
  Projects/App/Sources/DI/AppComponent+Home.swift
  Projects/Feature/HomeFeature/Demo/Resources/LaunchScreen.storyboard
  Projects/Feature/HomeFeature/Demo/Sources/AppDelegate.swift
  Projects/Feature/HomeFeature/Interface/HomeFactory.swift
  Projects/Feature/HomeFeature/Project.swift
  Projects/Feature/HomeFeature/Sources/DI/HomeComponent.swift
  Projects/Feature/HomeFeature/Sources/ViewControllers/HomeViewController.swift
  Projects/Feature/HomeFeature/Sources/ViewModels/HomeViewModel.swift
  Projects/Feature/HomeFeature/Testing/Testing.swift
  Projects/Feature/MainTabFeature/Project.swift
  Projects/Feature/MainTabFeature/Sources/DI/MainTabComponent.swift
  Projects/Feature/MainTabFeature/Sources/ViewControllers/MainTabBarController.swift
Labels: ✨ Feat

#60 🔀 :: 모듈 의존성 해결
  Projects/App/Sources/Application/NeedleGenerated.swift
  Projects/Feature/HomeFeature/Project.swift
  Projects/Feature/MainTabFeature/Sources/DI/MainTabComponent.swift
  Projects/Feature/MainTabFeature/Sources/ViewControllers/MainTabBarController.swift
  Projects/Feature/MyPageFeature/Sources/ViewControllers/MyPageContentViewController.swift
  Projects/Feature/RootFeature/Sources/ViewControllers/RootViewController.swift
  Projects/UserInterface/DesignSystem/Sources/ImageButton/ImageButton.swift
  graph.png
Labels: 🚑️ Hotfix

#62 🔀 :: 자잘한 이슈 해결
  Projects/Feature/MyPageFeature/Sources/ViewControllers/MyPageContentViewController.swift
Labels: 🚨 Fix

#64 🔀 :: 마이페이지 1차 마감
  Projects/Feature/MyPageFeature/Sources/ViewControllers/MyPageContentViewController.swift
  Projects/Feature/MyPageFeature/Sources/ViewModel/MyPageContentViewModel.swift
  Projects/Feature/MyPageFeature/Sources/Views/MyPageCategoryTableViewCell.swift
  Projects/Feature/MyPageFeature/Sources/Views/MyPageCollectionViewCell.swift
  Projects/Feature/MyPageFeature/Sources/Views/MyPageFooterView.swift
  Projects/Feature/MyPageFeature/Sources/Views/MyPageHeaderView.swift
  Projects/Feature/RootFeature/Sources/ViewControllers/RootViewController.swift
  Projects/Feature/SignInFeature/Demo/Sources/Views/LoginButtonView.swift
  Projects/Feature/SignInFeature/Sources/Views/LoginButtonView.swift
  Projects/UserInterface/DesignSystem/Resources/Image/Icon.xcassets/add.imageset/icon-plus-24@2x.png
  Projects/UserInterface/DesignSystem/Resources/Image/Icon.xcassets/add.imageset/icon-plus-24@3x.png
  Projects/UserInterface/DesignSystem/Resources/Image/Icon.xcassets/pencil.imageset/icon-edit-pencil-24@2x.png
  Projects/UserInterface/DesignSystem/Resources/Image/Icon.xcassets/pencil.imageset/icon-edit-pencil-24@3x.png
  Projects/UserInterface/DesignSystem/Resources/Image/Icon.xcassets/roundedX.imageset/x@2x.png
  Projects/UserInterface/DesignSystem/Resources/Image/Icon.xcassets/roundedX.imageset/x@3x.png
  Projects/UserInterface/DesignSystem/Sources/ImageButton/ImageButton.swift
Labels: ⚡️ Improve

#67 🔀 :: access 및 jwt 토큰 및 키체인 load , save 작업
  Projects/App/Sources/Application/SceneDelegate.swift
  Projects/Core/Network/Sources/API/AlleyAPI.swift
  Projects/Core/Network/Sources/Plugin/JwtPlugin.swift
  Projects/Domain/AuthDomain/Interface/DI/AuthDomainFactory.swift
  Projects/Domain/AuthDomain/Interface/DataSource/LocalAuthDataSource.swift
  Projects/Domain/AuthDomain/Interface/DataSource/RemoteAuthDataSource.swift
  Projects/Domain/AuthDomain/Interface/Entity/TokenEntity.swift
  Projects/Domain/AuthDomain/Interface/Entity/TokenTestEntity.swift
  Projects/Domain/AuthDomain/Interface/Repository/AuthRepository.swift
  Projects/Domain/AuthDomain/Interface/UseCase/FetchLoginUseCase.swift
  Projects/Domain/AuthDomain/Interface/UseCase/FetchTokenTestUseCase.swift
  Projects/Domain/AuthDomain/Sources/API/AuthAPI.swift
  Projects/Domain/AuthDomain/Sources/DI/AuthDomainComponent.swift
  Projects/Domain/AuthDomain/Sources/DTO/Request/LoginRequestDTO.swift
  Projects/Domain/AuthDomain/Sources/DTO/Response/TokenResponseDTO.swift
  Projects/Domain/AuthDomain/Sources/DTO/Response/TokenTestDTO.swift
  Projects/Domain/AuthDomain/Sources/DataSource/LocalAuthDataSourceImpl.swift
  Projects/Domain/AuthDomain/Sources/DataSource/RemoteAuthDataSourceImpl.swift
  Projects/Domain/AuthDomain/Sources/Repository/AuthRepositoryImpl.swift
  Projects/Domain/AuthDomain/Sources/UseCase/FetchLoginUseCaseImpl.swift
  Projects/Domain/AuthDomain/Sources/UseCase/FetchTokenTestUseCaseImpl.swift
  Projects/Domain/BaseDomain/Interface/interface.swift
  Projects/Domain/BaseDomain/Sources/DataSource/BaseRemoteDataSource.swift
  Projects/Feature/MyPageFeature/Sources/ViewControllers/MyPageContentViewController.swift
  Projects/Feature/MyPageFeature/Sources/Views/MyPageFooterView.swift
  Projects/Feature/SignInFeature/Sources/DI/SignInComponent.swift
  Projects/Feature/SignInFeature/Sources/ViewControllers/SignInViewController.swift
  Projects/Feature/SignInFeature/Sources/ViewModel/SignInViewModel.swift
  Projects/Shared/KeychainModule/Sources/DefaultKeychain.swift
  Projects/Shared/UtilityModule/Sources/Enum/LoginType.swift
  Projects/Shared/UtilityModule/Sources/Sources.swift
  Scripts/.swiftlint.yml
  graph.png
Labels: ⚡️ Improve

#70 홈뷰 UI 구현
  Projects/App/Sources/Application/SceneDelegate.swift
  Projects/Feature/HomeFeature/Sources/ViewControllers/HomeViewController.swift
  Projects/Feature/HomeFeature/Sources/Views/CategoryCollectionViewCell.swift
  Projects/Feature/HomeFeature/Sources/Views/ContentsCollectionViewCell.swift
  Projects/Feature/HomeFeature/Sources/Views/ContentsHeaderView.swift
  Projects/Feature/MainTabFeature/Sources/Sources.swift
  Projects/Feature/MainTabFeature/Sources/ViewControllers/MainTabBarController.swift
  Projects/Feature/SignInFeature/Sources/ViewControllers/SignInViewController.swift
  Projects/UserInterface/DesignSystem/Resources/Image/Icon.xcassets/search.imageset/Contents.json
  Projects/UserInterface/DesignSystem/Resources/Image/Icon.xcassets/search.imageset/Vector.png
  Projects/UserInterface/DesignSystem/Resources/Image/Icon.xcassets/search.imageset/Vector@2x.png
  Projects/UserInterface/DesignSystem/Resources/Image/Icon.xcassets/search.imageset/Vector@3x.png
  Projects/UserInterface/DesignSystem/Resources/Image/Logo.xcassets/homeLogo.imageset/Contents.json
  Projects/UserInterface/DesignSystem/Resources/Image/Logo.xcassets/homeLogo.imageset/Layer_1.png
  Projects/UserInterface/DesignSystem/Resources/Image/Logo.xcassets/homeLogo.imageset/Layer_1@2x.png
  Projects/UserInterface/DesignSystem/Resources/Image/Logo.xcassets/homeLogo.imageset/Layer_1@3x.png
  Projects/UserInterface/DesignSystem/Sources/Extensions/Extension+UIView.swift
  Projects/UserInterface/DesignSystem/Sources/SearchBar/SearchBar.swift
  graph.png
Labels: ✨ Feat

#73 디자인시스템 및 AlleyLabel 수정사항 적용
  Projects/UserInterface/DesignSystem/Sources/Font/Font+PrintingAlley.swift
  Projects/UserInterface/DesignSystem/Sources/Label/AlleyLabel.swift
  Projects/UserInterface/DesignSystem/Sources/Label/Extension+UILabel.swift
Labels: ⚡️ Improve

#78 🔀 :: 북마크 API 작업
  Plugin/DependencyPlugin/ProjectDescriptionHelpers/ModulePaths.swift
  Projects/App/Project.swift
  Projects/App/Sources/Application/NeedleGenerated.swift
  Projects/App/Sources/DI/AppComponent+AuthDomain.swift
  Projects/App/Sources/DI/AppComponent+BookMarkDomain.swift
  Projects/Core/Network/Sources/API/AlleyAPI.swift
  Projects/Domain/AuthDomain/Sources/UseCase/FetchLoginUseCaseImpl.swift
  Projects/Domain/BaseDomain/Interface/BaseEntity.swift
  Projects/Domain/BaseDomain/Interface/interface.swift
  Projects/Domain/BaseDomain/Sources/DTO/BaseResponseDTO.swift
  Projects/Domain/BookMarkDomain/Interface/DI/BookMarkDomainFactory.swift
  Projects/Domain/BookMarkDomain/Interface/DataSource/RemoteBookMarkDataSource.swift
  Projects/Domain/BookMarkDomain/Interface/Entity/MyBookMarkEntity.swift
  Projects/Domain/BookMarkDomain/Interface/Repository/BookMarkRepository.swift
  Projects/Domain/BookMarkDomain/Interface/UseCase/AddBookMarkUseCase.swift
  Projects/Domain/BookMarkDomain/Interface/UseCase/FetchMyBookMarksUseCase.swift
  Projects/Domain/BookMarkDomain/Interface/UseCase/GenerateBookMarkUseCase.swift
  Projects/Domain/BookMarkDomain/Interface/UseCase/LinkBookMarkUseCase.swift
  Projects/Domain/BookMarkDomain/Interface/UseCase/RemoveBookMarkGroupUseCase.swift
  Projects/Domain/BookMarkDomain/Interface/UseCase/RemoveBookMarkUseCase.swift
  Projects/Domain/BookMarkDomain/Project.swift
  Projects/Domain/BookMarkDomain/Sources/API/BookMarkAPI.swift
  Projects/Domain/BookMarkDomain/Sources/DI/BookMarkDomainComponent.swift
  Projects/Domain/BookMarkDomain/Sources/DTO/Request/AddBookMarkRequestDTO.swift
  Projects/Domain/BookMarkDomain/Sources/DTO/Request/GenerateBookMarkGroupRequestDTO.swift
  Projects/Domain/BookMarkDomain/Sources/DTO/Response/MyBookMarkResponseDTO.swift
  Projects/Domain/BookMarkDomain/Sources/DataSource/RemoteBookMarkDataSourceImpl.swift
  Projects/Domain/BookMarkDomain/Sources/Repository/BookMarkRepositoryImpl.swift
  Projects/Domain/BookMarkDomain/Sources/UseCase/AddBookMarkUseCaseImpl.swift
  Projects/Domain/BookMarkDomain/Sources/UseCase/FetchMyBookMarksUseCaseImpl.swift
  Projects/Domain/BookMarkDomain/Sources/UseCase/GenerateBookMarkUseCaseImpl.swift
  Projects/Domain/BookMarkDomain/Sources/UseCase/LinkBookMarkUseCaseImpl.swift
  Projects/Domain/BookMarkDomain/Sources/UseCase/RemoveBookMarkGroupUseCaseImpl.swift
  Projects/Domain/BookMarkDomain/Sources/UseCase/RemoveBookMarkUseCaseImpl.swift
  Projects/Feature/MyPageFeature/Sources/ViewControllers/MyPageViewController.swift
  graph.png
Labels: ⚡️ Improve

#91 🔀 :: 회원탈퇴 및 로그아웃 API 연결 및 테스트
  Plugin/DependencyPlugin/ProjectDescriptionHelpers/ModulePaths.swift
  Projects/App/Project.swift
  Projects/App/Sources/Application/NeedleGenerated.swift
  Projects/App/Sources/DI/Appcomponent+UserDomain.swift
  Projects/Core/Network/Sources/API/AlleyAPI.swift
  Projects/Domain/AuthDomain/Interface/DI/AuthDomainFactory.swift
  Projects/Domain/AuthDomain/Interface/DataSource/LocalAuthDataSource.swift
  Projects/Domain/AuthDomain/Interface/DataSource/RemoteAuthDataSource.swift
  Projects/Domain/AuthDomain/Interface/Entity/TokenEntity.swift
  Projects/Domain/AuthDomain/Interface/Repository/AuthRepository.swift
  Projects/Domain/AuthDomain/Interface/UseCase/LogOutUseCase.swift
  Projects/Domain/AuthDomain/Interface/UseCase/WithDrawUseCase.swift
  Projects/Domain/AuthDomain/Sources/API/AuthAPI.swift
  Projects/Domain/AuthDomain/Sources/DI/AuthDomainComponent.swift
  Projects/Domain/AuthDomain/Sources/DTO/Response/TokenResponseDTO.swift
  Projects/Domain/AuthDomain/Sources/DataSource/LocalAuthDataSourceImpl.swift
  Projects/Domain/AuthDomain/Sources/DataSource/RemoteAuthDataSourceImpl.swift
  Projects/Domain/AuthDomain/Sources/Repository/AuthRepositoryImpl.swift
  Projects/Domain/AuthDomain/Sources/UseCase/LogOutUseCaseImpl.swift
  Projects/Domain/AuthDomain/Sources/UseCase/WithDrawUseCaseImpl.swift
  Projects/Domain/UserDomain/Interface/DI/UserDomainFactory.swift
  Projects/Domain/UserDomain/Interface/DataSource/RemoteUserDataSource.swift
  Projects/Domain/UserDomain/Interface/Entity/UserInfoEntity.swift
  Projects/Domain/UserDomain/Interface/Repository/UserRepository.swift
  Projects/Domain/UserDomain/Interface/UseCase/FetchUserInfoUseCase.swift
  Projects/Domain/UserDomain/Interface/UseCase/RenameUserUseCase.swift
  Projects/Domain/UserDomain/Project.swift
  Projects/Domain/UserDomain/Sources/API/UserAPI.swift
  Projects/Domain/UserDomain/Sources/DI/UserDomainComponent.swift
  Projects/Domain/UserDomain/Sources/DTO/Request/RenameRequestDTO.swift
  Projects/Domain/UserDomain/Sources/DTO/Response/FetchUserInfoResponseDTO.swift
  Projects/Domain/UserDomain/Sources/DataSource/RemoteUserDataSourceImpl.swift
  Projects/Domain/UserDomain/Sources/Repository/UserRepositoryImpl.swift
  Projects/Domain/UserDomain/Sources/UseCase/FetchUserInfoUseCaseImpl.swift
  Projects/Domain/UserDomain/Sources/UseCase/RenameUserUseCaseImpl.swift
  Projects/Feature/BaseFeature/Project.swift
  Projects/Feature/BaseFeature/Sources/DI/EditModalComponent.swift
  Projects/Feature/BaseFeature/Sources/ViewControllers/EditModalViewController.swift
  Projects/Feature/BaseFeature/Sources/ViewModels/EditModalViewModel.swift
  Projects/Feature/MyPageFeature/Project.swift
  Projects/Feature/MyPageFeature/Sources/DI/MyPageContentComponent.swift
  Projects/Feature/MyPageFeature/Sources/ViewControllers/MyPage/MyPageViewController.swift
  Projects/Feature/MyPageFeature/Sources/ViewControllers/MyPageContent/MyPageContentViewController+Delegate.swift
  Projects/Feature/MyPageFeature/Sources/ViewControllers/MyPageContent/MyPageContentViewController+Input.swift
  Projects/Feature/MyPageFeature/Sources/ViewControllers/MyPageContent/MyPageContentViewController+Noti.swift
  Projects/Feature/MyPageFeature/Sources/ViewControllers/MyPageContent/MyPageContentViewController+Output.swift
  Projects/Feature/MyPageFeature/Sources/ViewControllers/MyPageContent/MyPageContentViewController.swift
  Projects/Feature/MyPageFeature/Sources/ViewModel/MyPageContentViewModel.swift
  Projects/Feature/SignInFeature/Project.swift
  Projects/Feature/SignInFeature/Sources/DI/SignInComponent.swift
  Projects/Feature/SignInFeature/Sources/ViewModel/SignInViewModel.swift
  Projects/Shared/UtilityModule/Sources/Enum/LoginType.swift
  Projects/Shared/UtilityModule/Sources/Extensions/Extension+Notification.Name.swift
  Projects/Shared/UtilityModule/Sources/PreferenceModel/UserInfo.swift
  Projects/Shared/UtilityModule/Sources/Utils/Utility.swift
  graph.png
Labels: ⚡️ Improve

#94 🔀 :: 스플래쉬 연결
  Projects/App/Sources/Application/NeedleGenerated.swift
  Projects/App/Sources/Application/SceneDelegate.swift
  Projects/Feature/MainTabFeature/Sources/ViewControllers/MainTabBarController.swift
  Projects/Feature/MyPageFeature/Sources/ViewControllers/MyPageContent/MyPageContentViewController+Output.swift
  Projects/Feature/MyPageFeature/Sources/ViewModel/MyPageContentViewModel.swift
  Projects/Feature/MyPageFeature/Sources/Views/MyPageFooterView.swift
  Projects/Feature/RootFeature/Project.swift
  Projects/Feature/RootFeature/Sources/DI/RootComponent.swift
  Projects/Feature/RootFeature/Sources/Sources.swift
  Projects/Feature/RootFeature/Sources/ViewControllers/RootViewController.swift
  Projects/Feature/RootFeature/Sources/ViewModel/RootViewModel.swift
Labels: ⚡️ Improve

#97 🔀 :: Verfiy API 연결
  Projects/Core/Network/Sources/Error/AlleyError.swift
  Projects/Domain/AuthDomain/Interface/DI/AuthDomainFactory.swift
  Projects/Domain/AuthDomain/Interface/DataSource/RemoteAuthDataSource.swift
  Projects/Domain/AuthDomain/Interface/Entity/TokenTestEntity.swift
  Projects/Domain/AuthDomain/Interface/Entity/VerifyEntity.swift
  Projects/Domain/AuthDomain/Interface/Repository/AuthRepository.swift
  Projects/Domain/AuthDomain/Interface/UseCase/VerifyUserUseCase.swift
  Projects/Domain/AuthDomain/Sources/API/AuthAPI.swift
  Projects/Domain/AuthDomain/Sources/DI/AuthDomainComponent.swift
  Projects/Domain/AuthDomain/Sources/DTO/Response/TokenTestDTO.swift
  Projects/Domain/AuthDomain/Sources/DTO/Response/VerifyResponseDTO.swift
  Projects/Domain/AuthDomain/Sources/DataSource/RemoteAuthDataSourceImpl.swift
  Projects/Domain/AuthDomain/Sources/Repository/AuthRepositoryImpl.swift
  Projects/Domain/AuthDomain/Sources/UseCase/VerifyUserUseCaseImpl.swift
  Projects/Feature/RootFeature/Sources/DI/RootComponent.swift
  Projects/Feature/RootFeature/Sources/ViewControllers/RootViewController.swift
  Projects/Feature/RootFeature/Sources/ViewModel/RootViewModel.swift
  Projects/Feature/SignInFeature/Sources/DI/SignInComponent.swift
  Projects/Feature/SignInFeature/Sources/ViewModel/SignInViewModel.swift
Labels: ⚡️ Improve

#102 🔀 홈 네트워크 연결
  Plugin/DependencyPlugin/ProjectDescriptionHelpers/ModulePaths.swift
  Projects/App/Project.swift
  Projects/App/Sources/Application/NeedleGenerated.swift
  Projects/App/Sources/DI/AppComponent+TagDomain.swift
  Projects/Core/Network/Sources/API/AlleyAPI.swift
  Projects/Domain/BaseDomain/Interface/ChildrenTagEntity.swift
  Projects/Domain/BaseDomain/Interface/PrintShopEntity.swift
  Projects/Domain/BaseDomain/Sources/DTO/ChildrenTagResponseDTO.swift
  Projects/Domain/BaseDomain/Sources/DTO/PrintShopResponseDTO.swift
  Projects/Domain/TagDomain/Interface/DI/TagDomainFactory.swift
  Projects/Domain/TagDomain/Interface/Datasource/RemoteTagDatasource.swift
  Projects/Domain/TagDomain/Interface/Entity/HierarchyEntity.swift
  Projects/Domain/TagDomain/Interface/Repository/TagRepository.swift
  Projects/Domain/TagDomain/Interface/UseCase/FetchHierarchyUseCase.swift
  Projects/Domain/TagDomain/Interface/UseCase/FetchTagUseCase.swift
  Projects/Domain/TagDomain/Project.swift
  Projects/Domain/TagDomain/Sources/API/TagAPI.swift
  Projects/Domain/TagDomain/Sources/DI/TagDomainComponent.swift
  Projects/Domain/TagDomain/Sources/DTO/Response/HierarchyResponseDTO.swift
  Projects/Domain/TagDomain/Sources/Datasource/RemoteTagDatasourceImpl.swift
  Projects/Domain/TagDomain/Sources/Repository/TagRepositoryImpl.swift
  Projects/Domain/TagDomain/Sources/UseCase/FetchHierarchyUseCaseImpl.swift
  Projects/Domain/TagDomain/Sources/UseCase/FetchTagToplevelUseCaseImpl.swift
  Projects/Feature/HomeFeature/Project.swift
  Projects/Feature/HomeFeature/Sources/DI/HomeComponent.swift
  Projects/Feature/HomeFeature/Sources/ViewControllers/HomeViewController.swift
  Projects/Feature/HomeFeature/Sources/ViewModels/HomeViewModel.swift
  Projects/Feature/HomeFeature/Sources/Views/CategoryCollectionViewCell.swift
  Projects/Feature/HomeFeature/Sources/Views/ContentsHeaderView.swift
Labels: ⚡️ Improve

#105 🔀 :: 필터 데모 앱 구현
  Projects/Domain/BaseDomain/Interface/ChildrenTagEntity.swift
  Projects/Feature/BaseFeature/Sources/ViewModels/EditModalViewModel.swift
  Projects/Feature/BaseFeature/Sources/Views/FilterButtonCollectionViewCell.swift
  Projects/Feature/HomeFeature/Demo/Sources/AppDelegate.swift
  Projects/Feature/HomeFeature/Demo/Sources/FilterSectionHeaderView.swift
  Projects/Feature/HomeFeature/Demo/Sources/FilterViewController.swift
  Projects/Feature/HomeFeature/Demo/Sources/SecondFilterTableViewCell.swift
  Projects/Feature/HomeFeature/Demo/Sources/TailFilterTableViewCell.swift
  Projects/Feature/HomeFeature/Demo/Sources/TopCellSectionFooterView.swift
  Projects/Feature/HomeFeature/Project.swift
  Projects/Feature/HomeFeature/Sources/ViewModels/HomeViewModel.swift
  Projects/UserInterface/DesignSystem/Sources/Button/FilterButton.swift
  Projects/UserInterface/DesignSystem/Sources/Layout/LeftAlignedCollectionViewFlowLayout.swift
  graph.png
Labels: ⚡️ Improve

#107 🔀 검색 네트워크 1차 구현
  Projects/Domain/BaseDomain/Interface/ChildrenTagEntity.swift
  Projects/Feature/BaseFeature/Sources/Views/FilterButtonCollectionViewCell.swift
  Projects/Feature/BaseFeature/Sources/Views/PrintingTableViewCell.swift
  Projects/Feature/SearchFeatue/Demo/Sources/Views/LeftAlignedCollectionViewFlowLayout.swift
  Projects/Feature/SearchFeatue/Sources/DI/SearchComponent.swift
  Projects/Feature/SearchFeatue/Sources/ViewControllers/AfterSearchViewController.swift
  Projects/Feature/SearchFeatue/Sources/ViewControllers/BeforeSearchViewController.swift
  Projects/Feature/SearchFeatue/Sources/ViewControllers/SearchViewController+Input.swift
  Projects/Feature/SearchFeatue/Sources/ViewControllers/SearchViewController+Output.swift
  Projects/Feature/SearchFeatue/Sources/ViewControllers/SearchViewController.swift
  Projects/Feature/SearchFeatue/Sources/ViewModels/AfterSearchViewModel.swift
  Projects/Feature/SearchFeatue/Sources/ViewModels/BeforeSearchViewModel.swift
  Projects/Feature/SearchFeatue/Sources/ViewModels/SearchViewModel.swift
  Projects/Feature/SearchFeatue/Sources/Views/View.swift
  Projects/UserInterface/DesignSystem/Sources/SearchBar/SearchBar.swift
  graph.png
Labels: 🚚 Move, ⚡️ Improve

#111 🔀 ::이미지 등록 테스트
  Plugin/DependencyPlugin/ProjectDescriptionHelpers/ModulePaths.swift
  Projects/App/Support/Info.plist
  Projects/Feature/BaseFeature/Sources/ViewModels/EditModalViewModel.swift
  Projects/Feature/ReviewFeature/Demo/Resources/LaunchScreen.storyboard
  Projects/Feature/ReviewFeature/Demo/Sources/AppDelegate.swift
  Projects/Feature/ReviewFeature/Demo/Sources/ReviewViewController.swift
  Projects/Feature/ReviewFeature/Demo/Sources/ReviewViewModel.swift
  Projects/Feature/ReviewFeature/Demo/Sources/TestAPI.swift
  Projects/Feature/ReviewFeature/Demo/Sources/TestDataSource.swift
  Projects/Feature/ReviewFeature/Demo/Sources/TestDataSourceImpl.swift
  Projects/Feature/ReviewFeature/Interface/Interface.swift
  Projects/Feature/ReviewFeature/Project.swift
  Projects/Feature/ReviewFeature/Sources/Sources.swift
  Projects/Feature/RootFeature/Project.swift
  Projects/Shared/UtilityModule/Sources/Protocols/RequestPermissionable.swift
  graph.png
Labels: ✨ Feat

#113 🔀 ::커스텀 페이지 컨트롤
  Projects/Feature/BaseFeature/Demo/Sources/AlleyPageViewController/AlleyPageViewController+DataSource.swift
  Projects/Feature/BaseFeature/Demo/Sources/AlleyPageViewController/AlleyPageViewController+Delegate.swift
  Projects/Feature/BaseFeature/Demo/Sources/AlleyPageViewController/AlleyPageViewController+Input.swift
  Projects/Feature/BaseFeature/Demo/Sources/AlleyPageViewController/AlleyPageViewController+Output.swift
  Projects/Feature/BaseFeature/Demo/Sources/AlleyPageViewController/AlleyPageViewController.swift
  Projects/Feature/BaseFeature/Demo/Sources/AlleyPageViewController/AlleyPageViewModel.swift
  Projects/Feature/BaseFeature/Demo/Sources/AppDelegate.swift
  Projects/Feature/BaseFeature/Demo/Sources/PageTitleCollectionViewCell.swift
  Projects/Feature/BaseFeature/Demo/Sources/PrintShopDetailViewController.swift
  Projects/Feature/BaseFeature/Demo/Sources/PrintShopPhotosCollectionViewCell.swift
  Projects/Shared/UtilityModule/Sources/Extensions/Extension+UIButton.swift
  Projects/UserInterface/DesignSystem/Resources/Image/Logo.xcassets/tmpPrintShop.imageset/Contents.json
  Projects/UserInterface/DesignSystem/Resources/Image/Logo.xcassets/tmpPrintShop.imageset/Rectangle 169@2x.png
  Projects/UserInterface/DesignSystem/Resources/Image/Logo.xcassets/tmpPrintShop.imageset/Rectangle 169@3x.png
Labels: ⚡️ Improve

#118 🔀 검색 네트워크 중간 구현
  Projects/App/Sources/Application/NeedleGenerated.swift
  Projects/App/Sources/DI/Appcomponent+Search.swift
  Projects/Domain/SearchDomain/Sources/Datasource/RemoteSearchDatasourceImpl.swift
  Projects/Domain/SearchDomain/Sources/Repository/SearchRepositoryImpl.swift
  Projects/Domain/SearchDomain/Sources/UseCase/FetchPrintShopListUseCaseImpl.swift
  Projects/Feature/SearchFeatue/Interface/SearcyFactory.swift
  Projects/Feature/SearchFeatue/Sources/DI/AfterSearchComponent.swift
  Projects/Feature/SearchFeatue/Sources/DI/BeforeSearchComponent.swift
  Projects/Feature/SearchFeatue/Sources/DI/SearchComponent.swift
  Projects/Feature/SearchFeatue/Sources/ViewControllers/AfterSearchViewController.swift
  Projects/Feature/SearchFeatue/Sources/ViewControllers/SearchViewController+Input.swift
  Projects/Feature/SearchFeatue/Sources/ViewControllers/SearchViewController+Output.swift
  Projects/Feature/SearchFeatue/Sources/ViewControllers/SearchViewController.swift
  Projects/Feature/SearchFeatue/Sources/ViewModels/AfterSearchViewModel.swift
  Projects/Feature/SearchFeatue/Sources/ViewModels/SearchViewModel.swift
Labels: ⚡️ Improve
